services:
  homeassistant:
    container_name: homeassistant
    image: docker.io/homeassistant/home-assistant:stable
    volumes:
      - /home/enricocoppolecchia/sources/docker-sandbox/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

